### ISSUE TITLE
On SIGTERM, cancel current task and stop

### ISSUE THREAD

**Issue by JohanLorenzo** [mozilla-releng/scriptworker#260] opened 2018-09-21 14:56 UTC
[pushsnapscript](https://github.com/mozilla-releng/pushapkscript) is the kind of worker that doesn't output anything for several minutes (this is a limitation of [snapcraft](https://github.com/snapcore/snapcraft)). It also takes a while to complete. Therefore, scriptworker has to reclaim the task, at least once.

RyanVM discovered: https://tools.taskcluster.net/groups/YndHp56KRGiPUmmt0tNd0Q/tasks/dzTJrSbLQ96gqd7sVZuk1A/runs/0

There is no logs for run 0 on Taskcluster, but here are the ones on the worker:

```
2018-09-21T13:37:29     INFO - Pushing target.snap
[                                                    ]   0% Pushing target.snap
[===                                                 ]   6% Pushing target.snap
[======                                              ]  12% Pushing target.snap
[=========                                           ]  18% Pushing target.snap
[============                                        ]  24% Pushing target.snap
[===============                                     ]  30% Pushing target.snap
[==================                                  ]  36% Pushing target.snap
[=====================                               ]  42% Pushing target.snap
[=========================                           ]  48% Pushing target.snap
[============================                        ]  54% Pushing target.snap
[===============================                     ]  60% Pushing target.snap
[==================================                  ]  66% Pushing target.snap
[=====================================               ]  72% Pushing target.snap
[========================================            ]  78% Pushing target.snap
[===========================================         ]  84% Pushing target.snap
[==============================================      ]  90% Pushing target.snap
[==================================================  ]  96% Pushing target.snap
[====================================================]  100% Pushing target.snap
2018-09-21T13:39:35    DEBUG - Reclaiming task...
2018-09-21T13:39:36    DEBUG - Reclaim task response:
{'credentials': '{********}',
 'runId': 0,
 'status': {'deadline': '2018-09-22T13:34:18.351Z',
            'expires': '2019-09-21T13:34:18.351Z',
            'provisionerId': 'scriptworker-prov-v1',
            'retriesLeft': 5,
            'runs': [{'reasonCreated': 'scheduled',
                      'runId': 0,
                      'scheduled': '2018-09-21T13:34:34.263Z',
                      'started': '2018-09-21T13:34:35.194Z',
                      'state': 'running',
                      'takenUntil': '2018-09-21T13:59:35.934Z',
                      'workerGroup': 'pushsnap-v1',
                      'workerId': 'pushsnapworker-1'}],
            'schedulerId': 'gecko-level-3',
            'state': 'running',
            'taskGroupId': 'YndHp56KRGiPUmmt0tNd0Q',
            'taskId': 'dzTJrSbLQ96gqd7sVZuk1A',
            'workerType': 'pushsnap-v1'},
 'takenUntil': '2018-09-21T13:59:35.934Z',
 'workerGroup': 'pushsnap-v1',
 'workerId': 'pushsnapworker-1'}
2018-09-21T13:39:36    DEBUG - waiting 300 seconds before reclaiming...
2018-09-21T13:43:27     INFO - SIGTERM received; shutting down after next task
2018-09-21T13:43:39     INFO - Scriptworker starting up at 2018-09-21 13:43:39+00:00 UTC
2018-09-21T13:43:39    DEBUG - rm(/builds/scriptworker/work)
2018-09-21T13:43:39    DEBUG - makedirs(/builds/scriptworker/work)
2018-09-21T13:43:39    DEBUG - rm(/builds/scriptworker/artifacts)
2018-09-21T13:43:39    DEBUG - makedirs(/builds/scriptworker/artifacts)
2018-09-21T13:43:39    DEBUG - makedirs(/builds/scriptworker/artifacts/public/logs)
2018-09-21T13:43:39    DEBUG - Calling claimWork...
2018-09-21T13:43:40     INFO - rebuild_gpg_homedirs()...
2018-09-21T13:43:40     INFO - Updating git repo
2018-09-21T13:43:40     INFO - rebuilding gpg_home for /home/cltbld/pubkey at /tmp/tmp7bj8zlsv...
```

As you can see, once SIGTERM is received, the task is immediately killed. That explains why no logs were uploaded. Moreover the 300 seconds weren't waited on.

**Comment by escapewindow** [comment] 2018-09-21 22:48
Hm, something may be broken [here](https://github.com/mozilla-releng/scriptworker/blob/master/scriptworker/worker.py#L173-L187), though I'm not currently seeing what.

**Comment by mitchhentges** [comment] 2018-11-20 02:46
I'm attempting to reproduce this in by having a build take over 10 minutes (I've just configured `scriptworker` to invoke `signingscript`, which I've modified with a `time.sleep(600)`). However, regardless of if I:

* Start the build, then `SIGINT` the `scriptworker` process
* Start the build, wait for the first re-claim (5 minutes), then `SIGINT` the `scriptworker` process

Either way, the `scriptworker` process doesn't end until the child does, at which point the logs are properly uploaded.

Is there additional information I can use to reproduce the problem (or perhaps I'm misunderstanding something?).
Otherwise, I'll continue tomorrow to get `pushsnapscript` running locally - perhaps there's something specific to `pushsnapscript` that trigger this bug

**Comment by JohanLorenzo** [comment] 2018-11-20 13:34
Thank you for the investigation, Mitch! 

I looked back at the rerun jobs[1] and I was able to find a single occurrence since I filed this issue. It's actually the task referenced above. This implies 2 things, to me:

a. either it's be hard to reproduce the bug, or we're still missing some conditions to retrigger it
b. the impact is low (as only one job got its logs missing). Moreover, a `claim-expired` task is automatically rerun, so it appears (on Treeherder) in a category sheriffs don't have to act on.

Regarding a., we can try a few things:

* Use `SIGTERM` instead of `SIGINT`: `kill -TERM $PID_OF_SCRIPTWORKER`. 
* Let scriptworker call a different program which [turns into a zombie](https://en.wikipedia.org/wiki/Zombie_process#Examples) (I wonder whether that happened to pushsnapscript).
* Kill the child process with [different signals](http://man7.org/linux/man-pages/man7/signal.7.html) (`SIGPIPE`, `SIGHUP`, or `SIGABRT` may be good candidates).

In my opinion, it's not worth trying to run `pushsnapscript` locally, yet. `pushsnapscript` isn't in a great shape to work locally because of [these constraints](https://bugzilla.mozilla.org/show_bug.cgi?id=1447263#c15).

Because of b., I wonder if it's worth investigating much on this issue. If none of the things listed above works, it may just be better to leave the issue open until it happens again (and someone notices it). What do you all think? 

[1] For instance, on mozilla-beta: https://treeherder.mozilla.org/#/jobs?repo=mozilla-beta&resultStatus=retry%2Crunnable&searchStr=snap, then expand the list 50 by 50.

**Comment by mitchhentges** [comment] 2018-11-20 19:09
I played around with some signals and found that:

* Interestingly, when the child process (e.g. `signingscript`) dies (due to `SIGPWR`, `SIGKILL`, `SIGSEGV` etc), `scriptworker` [assumes that it's a success](https://tools.taskcluster.net/groups/Qn_DXY0qSE6NEylj6OYFpw/tasks/HZOWNprRQ-yDviaTangbyA/details). Perhaps if the child dies, it shouldn't be marked as green? Reported as #274
* For this specific bug, the linked build shows the output "SIGTERM received; shutting down after next task". Looking at [the code that prints that](https://github.com/mozilla-releng/scriptworker/blob/master/scriptworker/worker.py#L175-L180), I'm pretty confident that this exact bug won't be reproduced by anything other than `SIGTERM` on the `scriptworker` process.
    * Note that other signals, such as `SIGKILL` on `scriptworker`, make the build hang. However, IMHO, I think this is expected - if our process is insta-killed, it's very difficult to inform TC that work has stopped.
    * I might be missing some kind of state that's required to reproduce the bug, or perhaps this bug requires precise timing to trigger. Either way, based on the limited impact, I'll leave this bug for now until we know more about it (and it becomes easier to reproduce)

**Comment by JohanLorenzo** [comment] 2018-11-21 10:22
Great finding, @mitchhentges! 

Okay to leave this bug as is, for now.

**Comment by mitchhentges** [comment] 2019-01-17 00:03
I found a way to reproduce this (on the build agents, not sure about locally):

1. SSH into remote worker (e.g.: `dep-m-signing-linux-1.srv.releng.use1.mozilla.com`)
2. In another terminal, log into your `taskcluster` CLI
3. Find a signing task that you'll use to reproduce the problem, like [this one](https://taskcluster-web.netlify.com/tasks/Zq9m4s9qQsqFYPfVMYJkkw/runs/3)
4. Immediately back-to-back, do:
    1. In the terminal with `taskcluster`, do `taskcluster task rerun $taskid`
    2. In the SSH terminal, run `sudo supervisorctl restart signing_scriptworker`
5. Even after `supervisorctl` finishes restarting, the build will sit at "running"

**Comment by escapewindow** [comment] 2019-01-17 02:07
Ah, there's no `worker-shutdown` status update on scriptworker exit. We could add that, as well as log uploads, but that means scriptworker will take longer to shut down, and we'll still hit this if we `kill -9`.

**Comment by mitchhentges** [comment] 2019-01-17 06:16
I think there'll be benefit to adding it, because it specifically addresses the problem where we restart scriptworker with `supervisorctl`, but our most-recent task hangs.

Note: I still can't seem to reproduce this problem locally with `SIGTERM` - maybe `supervisorctl` gets more aggressive as time goes by

**Comment by JohanLorenzo** [comment] 2019-01-17 10:57
Excellent work on finding the steps to reproduce! It sounds like this issue and #131 are the same one, aren't they?

**Comment by mitchhentges** [comment] 2019-01-17 17:45
They could be related, but since I can't reproduce locally, I'm wondering if there's more going on here :thinking:

**Comment by escapewindow** [comment] 2019-01-17 18:17
> Excellent work on finding the steps to reproduce! It sounds like this issue and #131 are the same one, aren't they?

If these STR are the only ones we're concerned about, yes, this is a dup of #131.

**Comment by mitchhentges** [comment] 2019-01-24 19:00
There's definitely something interesting happening with `supervisord`.
If I `supervisorctl restart *_scriptworker` while mid-build, the build never changes state beyond "completed".
Meanwhile, if I run `scriptworker` manually (on the exact same worker instance with the exact same config), then `SIGTERM` the process mid-build, then `scriptworker` waits until the build finishes (setting the "completed" status) and shuts down.

I'm guessing that `supervisord` increases the severity of kill signals over time? If that's the case, then I'm not sure that adding logic to `scriptworker` will help here, since the script might be being killed before it can do clean-up logic.

**Comment by escapewindow** [comment] 2019-01-24 19:08
Hm. It's possible we won't use `supervisord` on the docker images. Not sure.

If we don't use `supervisord` on the docker images, we can potentially shut down more gracefully, and shut down the docker container. Meanwhile we either need to live with this or find an acceptable solution or workaround for the puppet-controlled daemons.

**Comment by mitchhentges** [comment] 2019-01-24 19:11
I'm being a little extra-verbose here so that I keep track of what's going on as I go.
Right now, I'm trying to detect which signals are hitting our `scriptworker` instance (maybe there's a `SIGKILL` going on?). Once I know that, perhaps `supervisord` can be configured to be more compliant, or we can maybe increase our signal suppression.

A final, worst-comes-to-worst solution is, rather than trying to finish our current build before shutdown (which is why we take so long to respond to `SIGTERM`), we can just insta-mark the build as failed with reason "worker shutdown". Fingers crossed it doesn't come to this

**Comment by escapewindow** [comment] 2019-01-24 19:20
Yeah. Another possibility is scriptworker, on startup, could check for recent task info on disk. (This may mean we cache the full `claimWork` response on disk somewhere, and clean it up after we finish a task?) If it looks like we shut down too soon, we can check the task status and mark as worker-shutdown if needed.

**Comment by mitchhentges** [comment] 2019-01-24 19:22
I'd be nervous about that solution, because if a machine or instance is shut down without being started back up (immediately) afterwards, we'll still have an incorrect status being reported.

**Comment by escapewindow** [comment] 2019-01-24 20:24
It'll automatically be marked worker-shutdown within 20min anyway, and if it's already resolved scriptworker won't be able to re-resolve it. This basically avoids an up-to 20minute waiting period for the task to be re-scheduled.

**Comment by escapewindow** [comment] 2019-01-24 20:33
> Sorry, I don't fully understand:
> 
> > It'll automatically be marked worker-shutdown within 20min anyway
> 
> If a task goes beyond 20 minutes, it's automatically marked as `worker-shutdown` - even if the worker itself (`scriptworker`) doesn't report that?

Sorry, `claim-expired`, which re-schedules the task.

> > if it's already resolved scriptworker won't be able to re-resolve it.
> 
> As in, if the build succeeded, if the worker tries to update the status on-startup, it won't be able to (because the build already succeeded and the status was already set to "resolved"?)

Correct. Or failed, or exception. Scriptworker would only be able to resolve the taskId/runId if it's not already resolved.

> > This basically avoids an up-to 20minute waiting period for the task to be re-scheduled.
> 
> If there's a 20 minute timeout before the task's status is set to `worker-shutdown`, how is that waiting period avoided?

We need to reclaim the task every 20min or we hit `claim-expired` and the queue reschedules the task, whether scriptworker is still running or not. So if we do nothing, all our killed, unresolved tasks will rerun after 20min, which is what the situation is today. Ideally we report `worker-shutdown` when we know we are either imminently shutting down, or after we start back up and notice that we haven't resolved the previous task, to cut this 20min window down.

**Comment by mitchhentges** [comment] 2019-01-24 21:33
Ah, ok, if I understand correctly, solution/behaviour you're recommending is:

1. On startup, check for recent task activity
2. If yes, then tell Taskcluster that there was a `worker-shutdown`
* Net effect: rather than 20 minutes before a task is restarted, a task is instead restarted in `$(time it takes before scriptworker is running again)`

I'm a little nervous about the extra states that this forces us to manage:
* Are we recording task information to disk on-worker-shutdown? If so, we have a limited, constant amount of time between the "shut down will happen" (`SIGINT`) and `scriptworker` being killed.
    * What happens if the task information isn't recorded in time?
    * What happens if the task information is _partially_ recorded (killed halfway through recording). Is this even possible?
* On worker startup:
    * Need to handle sending `worker-shutdown` if there's task information
    * What if the task information is incomplete/corrupt/partially recorded?
    * What if the child process running the task (e.g.: scriptworker) is still running (right through the `scriptworker` restart)? Will it report anything when it finishes? Do we still want to report `worker-shutdown`? Can we still properly detect failures, since that process has been adopted (`scriptworker` is no longer the parent process, since it was restarted)
* What about if a machine is stopped without being restarted? We will still have a situation where a build is still showing as "running" (for 20 minutes), even though the worker was stopped
* What if Taskcluster changes its behaviour to allow overwriting a build result (e.g.: on worker startup, we're automatically sending `worker-shutdown` but depending on it being ignored if the build succeeded)?

-----

I'm guessing that the behaviour that `supervisord` is hoping to guide with it's "`SIGTERM`, delay, then `SIGKILL`" behaviour is for programs to close down and clean up as fast as possible upon the `SIGTERM` (finishing before a `SIGKILL` is needed).

Perhaps we'd be most compliant and have the best-of-both-worlds if we:
* Upon receiving `SIGTERM`:
    * If we don't have a current task, stop immediately
    * If we do have a current task:
        * Tell that task to stop (`SIGTERM`) - our scripts should stop nearly immediately
        * Tell taskcluster that the task failed with `worker-shutdown`
* Upon startup, behave like normal

This keeps all of our logic for "shutdown while a task is active" contained and reduces the amount of questions we need to handle

**Comment by escapewindow** [comment] 2019-01-24 21:40
Sure :) Yeah, if the `SIGTERM` to the task is async we can submit `worker-shutdown` concurrently. Makes sense. Ideally we also upload any in-progress logs and artifacts, which increases the time to shutdown.

**Comment by mitchhentges** [comment] 2019-01-24 21:42
We have 10 seconds between `SIGTERM` and `SIGKILL`, so I think we should safely be able to update Taskcluster with our current state :)

**Closed** 2019-02-14 01:09 UTC
